fastlane_version "2.98.0"
REQUIRED_XCODE_VERSION = "9.4"
default_platform :ios

platform :ios do
  desc "Increment the version and build number"
  lane :version_bump_project do |options|    
    version_number = increment_version_number_in_plist(
      xcodeproj: './PremierKit.xcodeproj',
      target: 'PremierKit',
      bump_type: options[:bump_type],
    )
    # Set build number to current date and time
    build_number = Time.new.strftime("%Y.%m.%d.%H.%M")
    increment_build_number_in_plist(
      xcodeproj: './PremierKit.xcodeproj',
      target: 'PremierKit',
      build_number: build_number,
    )
  end

  desc "Prepare a new Release version"
  lane :release do |options|
    version_bump_project bump_type: options[:bump]
    version_bump_podspec bump_type: options[:bump]
    clean_build_artifacts
  end
end
