on: pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test - ${{ matrix.destination }}
        run: |
          sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer; xcodebuild -version
          xcodebuild clean test -project PremierKit.xcodeproj -scheme PremierKit -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
